In [1]:
import numpy as np
import os

# Path to the .npy file
file_path = '/Users/rohith/Desktop/M3D copy/Data/data/examples/example_06.npy'

# Check if the file exists
if os.path.exists(file_path):
    # Load the .npy file
    data = np.load(file_path)
    
    # Print the basic information about the file
    print(f"Data type: {data.dtype}")
    print(f"Data shape: {data.shape}")
    
    # Display the first few elements (or slices if multidimensional)
    print("Data sample:", data if data.ndim == 1 else data[0])
    
    # Determine if it's suitable for image conversion
    if data.ndim == 3 or data.ndim == 4:  # Assuming the data is an image or slices of images
        print(f"The data has {data.shape[0]} slices.")
    else:
        print("This data does not appear to be an image or volumetric slices.")
else:
    print(f"File not found at {file_path}")


Data type: float32
Data shape: (1, 32, 256, 256)
Data sample: [[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  

In [2]:
import numpy as np
from PIL import Image
import os

# Path to the .npy file
file_path = '/Users/rohith/Desktop/M3D copy/Data/data/examples/example_06.npy'

# Load the .npy file
data = np.load(file_path)

# Remove the first dimension (batch dimension), now shape is (32, 256, 256)
slices = data[0]  # Shape: (32, 256, 256)

# Directory to save the output images
output_dir = 'output_images'
os.makedirs(output_dir, exist_ok=True)

# Loop through each slice and save it as a PNG
for i in range(slices.shape[0]):
    # Normalize the slice data (convert float32 to 0-255 range)
    slice_data = slices[i]
    slice_normalized = (slice_data - np.min(slice_data)) / (np.max(slice_data) - np.min(slice_data)) * 255
    slice_normalized = slice_normalized.astype(np.uint8)  # Convert to uint8

    # Convert to an image and save as PNG
    img = Image.fromarray(slice_normalized)
    output_path = os.path.join(output_dir, f'slice_{i}.png')
    img.save(output_path)
    print(f'Slice {i} saved as {output_path}')


Slice 0 saved as output_images/slice_0.png
Slice 1 saved as output_images/slice_1.png
Slice 2 saved as output_images/slice_2.png
Slice 3 saved as output_images/slice_3.png
Slice 4 saved as output_images/slice_4.png
Slice 5 saved as output_images/slice_5.png
Slice 6 saved as output_images/slice_6.png
Slice 7 saved as output_images/slice_7.png
Slice 8 saved as output_images/slice_8.png
Slice 9 saved as output_images/slice_9.png
Slice 10 saved as output_images/slice_10.png
Slice 11 saved as output_images/slice_11.png
Slice 12 saved as output_images/slice_12.png
Slice 13 saved as output_images/slice_13.png
Slice 14 saved as output_images/slice_14.png
Slice 15 saved as output_images/slice_15.png
Slice 16 saved as output_images/slice_16.png
Slice 17 saved as output_images/slice_17.png
Slice 18 saved as output_images/slice_18.png
Slice 19 saved as output_images/slice_19.png
Slice 20 saved as output_images/slice_20.png
Slice 21 saved as output_images/slice_21.png
Slice 22 saved as output_image